image: $REGISTRY_CI/gitlab-ci-base:buster

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  GIT_DEPTH: 10
  RELEASE_NAME: ${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}

services:
  - docker:19.03.1-dind

stages:
  - build-test
  - test
  - build
  - deploy

#########################
####  TEMPLATE      ####
########################

.test_template: &test_definition
  allow_failure: false
  before_script:
    - sed -i -e "s/{SMTP_LINK\}/common-smtp:1025/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_APPLEPAY_USERNAME_TEST\}/$HIPAY_APPLEPAY_USERNAME_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_APPLEPAY_PASSWORD_TEST\}/$HIPAY_APPLEPAY_PASSWORD_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_APPLEPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_APPLEPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{ACTIVE_METHODS\}/$ACTIVE_METHODS/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{GITHUB_API_TOKEN\}/$GITHUB_TOKEN/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{GITLAB_API_TOKEN\}/$GITLAB_API_TOKEN/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PUBLIC_KEY\}/$MAGE_ACCOUNT_PUBLIC_KEY/" ./bin/docker/conf/test/auth.env.sample
    - sed -i -e "s/{MAGE_ACCOUNT_PRIVATE_KEY\}/$MAGE_ACCOUNT_PRIVATE_KEY/" ./bin/docker/conf/test/auth.env.sample
    - sed -i "s/$(echo "{BRANCH}" | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $CI_COMMIT_REF_NAME | sed -e 's/[\/&]/\\&/g')/g" ./bin/docker/conf/test/module.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/test/hipay.env.sample
  tags:
    - gcp-high-load-runner-prod
  artifacts:
    paths:
      - bin/tests/errors
    when: always

#########################
####      JOBS      ####
########################

build-test-2-1-10:
  stage: build-test
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml push
  tags:
    - gcp-default-runner-prod

casperjs-2-1-10:
  <<: *test_definition
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml pull -q
    - docker-compose -f docker-compose.test.yml up -d
    - until docker-compose -f docker-compose.test.yml logs | grep -m 1 "DOCKER MAGENTO TO HIPAY stage IS UP" ; do sleep 1 ; done
    - docker-compose -f docker-compose.test.yml logs
    - curl --retry 10 --retry-delay 20 -v http:\/\/127.0.0.1:8096/
    - sh bin/tests/casper_run_circle.sh http:\/\/127.0.0.1:8096
  tags:
    - gcp-high-load-runner-prod

build:
  stage: build
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  when: manual
  script:
    - docker build -f bin/docker/images/default/Dockerfile . -t ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web:${CI_COMMIT_REF_SLUG}
    - /tools/auth-as-end-user.sh
    - docker push ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web:${CI_COMMIT_REF_SLUG}
    - /tools/logout-end-user.sh
  tags:
    - gcp-default-runner-prod

deploy2recette:
  stage: deploy
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  when: manual
  variables:
    GPC_ACCOUNT: ''
  script:
    - echo $RELEASE_NAME
    - /tools/auth-to-cd-cluster.sh
    - >
      helm install $RELEASE_NAME ./bin/docker/kubernetes/helm/
      --set magento2_image="${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web"
      --set magento2_tag="${CI_COMMIT_REF_SLUG}"
      --set magento2_url="${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.${PI_CD_URL}"
      --set github_api_token="${GITHUB_TOKEN}"
      --set gitlab_api_token="${GITLAB_API_TOKEN}"
      --set mage_account_public_key="${MAGE_ACCOUNT_PUBLIC_KEY}"
      --set mage_account_private_key="${MAGE_ACCOUNT_PRIVATE_KEY}"
      --set hipay_api_user_test="$HIPAY_API_USER_RE7"
      --set hipay_api_password_test="$HIPAY_API_PASSWORD_RE7"
      --set hipay_secret_passphrase_test="$HIPAY_SECRET_PASSPHRASE_RE7"
      --set hipay_tokenjs_username_test="$HIPAY_TOKENJS_USERNAME_RE7"
      --set hipay_tokenjs_publickey_test="$HIPAY_TOKENJS_PUBLICKEY_RE7"
      --set hipay_applepay_username_test="$HIPAY_APPLEPAY_USERNAME_RE7"
      --set hipay_applepay_password_test="$HIPAY_APPLEPAY_PASSWORD_RE7"
      --set hipay_applepay_secret_passphrase_test="$HIPAY_APPLEPAY_SECRET_PASSPHRASE_RE7"
      --set pi_data_url="$PI_CI_DATA_URL"
      --set branch="$CI_COMMIT_REF_NAME"
    - /tools/logout-end-user.sh
  allow_failure: true
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: https://${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.${PI_CD_URL}
    on_stop: stop_review
  only:
    - branches
  tags:
    - gcp-default-runner-prod

stop_review:
  stage: deploy
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  variables:
    GIT_STRATEGY: none
  script:
    - /tools/auth-to-cd-cluster.sh
    - helm uninstall $RELEASE_NAME
    - /tools/logout-end-user.sh
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - gcp-default-runner-prod
